MOVIES = [
    {"title": "The Shawshank Redemption", "genres": "Drama Crime"},
    {"title": "The Godfather", "genres": "Crime Drama"},
    {"title": "The Dark Knight", "genres": "Action Crime Thriller"},
    {"title": "Pulp Fiction", "genres": "Crime Drama"},
    {"title": "Fight Club", "genres": "Drama Thriller"},
    {"title": "Forrest Gump", "genres": "Drama Romance"},
    {"title": "Inception", "genres": "Action Sci-Fi Thriller"},
    {"title": "The Matrix", "genres": "Action Sci-Fi"},
    {"title": "Interstellar", "genres": "Sci-Fi Drama Adventure"},
    {"title": "The Silence of the Lambs", "genres": "Thriller Horror Crime"},
    {"title": "Se7en", "genres": "Thriller Crime Mystery"},
    {"title": "Goodfellas", "genres": "Crime Drama"},
    {"title": "Schindler's List", "genres": "Drama History War"},
    {"title": "Spirited Away", "genres": "Animation Fantasy Adventure"},
    {"title": "The Lion King", "genres": "Animation Family Adventure"},
    {"title": "Toy Story", "genres": "Animation Family Comedy"},
    {"title": "Finding Nemo", "genres": "Animation Family Adventure"},
    {"title": "Avatar", "genres": "Action Sci-Fi Adventure"},
    {"title": "The Avengers", "genres": "Action Sci-Fi Adventure"},
    {"title": "Titanic", "genres": "Romance Drama Disaster"},
    {"title": "Jurassic Park", "genres": "Action Adventure Sci-Fi"},
    {"title": "Star Wars: A New Hope", "genres": "Sci-Fi Action Adventure"},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "genres": "Fantasy Adventure Action"},
    {"title": "Harry Potter and the Sorcerer's Stone", "genres": "Fantasy Adventure Family"},
    {"title": "Gladiator", "genres": "Action Drama History"},
    {"title": "The Departed", "genres": "Crime Drama Thriller"},
    {"title": "Saving Private Ryan", "genres": "War Drama Action"},
    {"title": "Django Unchained", "genres": "Western Drama Action"},
    {"title": "The Wolf of Wall Street", "genres": "Comedy Crime Drama"},
    {"title": "Joker", "genres": "Drama Thriller Crime"},
    {"title": "Avengers: Endgame", "genres": "Action Sci-Fi Adventure"},
    {"title": "Spider-Man: Into the Spider-Verse", "genres": "Animation Action Adventure"},
    {"title": "The Grand Budapest Hotel", "genres": "Comedy Adventure"},
    {"title": "Whiplash", "genres": "Drama Music"},
    {"title": "La La Land", "genres": "Romance Musical Drama"},
    {"title": "Parasite", "genres": "Thriller Comedy Drama"},
    {"title": "The Social Network", "genres": "Drama Biography"},
    {"title": "Coco", "genres": "Animation Family Fantasy"},
    {"title": "Zootopia", "genres": "Animation Family Comedy"},
    {"title": "Mad Max: Fury Road", "genres": "Action Sci-Fi Adventure"},
    {"title": "The Prestige", "genres": "Drama Thriller Mystery"},
    {"title": "Memento", "genres": "Thriller Mystery Crime"},
    {"title": "The Terminator", "genres": "Sci-Fi Action Thriller"},
    {"title": "Alien", "genres": "Horror Sci-Fi Thriller"},
    {"title": "The Shining", "genres": "Horror Thriller Drama"},
    {"title": "Get Out", "genres": "Horror Thriller Mystery"},
    {"title": "A Quiet Place", "genres": "Horror Sci-Fi Thriller"},
    {"title": "John Wick", "genres": "Action Thriller Crime"},
    {"title": "Fast & Furious", "genres": "Action Crime Thriller"},
    {"title": "Mission: Impossible - Fallout", "genres": "Action Thriller Adventure"},
    {"title": "The Notebook", "genres": "Romance Drama"},
    {"title": "Pride and Prejudice", "genres": "Romance Drama"},
    {"title": "Deadpool", "genres": "Action Comedy Sci-Fi"},
    {"title": "Guardians of the Galaxy", "genres": "Action Sci-Fi Comedy"},
    {"title": "Wonder Woman", "genres": "Action Fantasy Adventure"},
    {"title": "The Wizard of Oz", "genres": "Fantasy Adventure Musical"},
    {"title": "E.T. the Extra-Terrestrial", "genres": "Sci-Fi Family Adventure"},
    {"title": "Back to the Future", "genres": "Sci-Fi Comedy Adventure"},
    {"title": "The Exorcist", "genres": "Horror Thriller"},
    {"title": "Psycho", "genres": "Horror Thriller Mystery"},
    {"title": "Jaws", "genres": "Thriller Horror Adventure"},
    {"title": "The Truman Show", "genres": "Comedy Drama Sci-Fi"},
    {"title": "Groundhog Day", "genres": "Comedy Romance Fantasy"},
    {"title": "Casablanca", "genres": "Romance Drama War"},
    {"title": "Gone with the Wind", "genres": "Romance Drama History"},
    {"title": "12 Angry Men", "genres": "Drama Crime"},
    {"title": "One Flew Over the Cuckoo's Nest", "genres": "Drama Comedy"},
    {"title": "Braveheart", "genres": "Drama History War"},
    {"title": "The Green Mile", "genres": "Drama Crime Fantasy"},
    {"title": "No Country for Old Men", "genres": "Thriller Crime Western"},
    {"title": "There Will Be Blood", "genres": "Drama History"},
    {"title": "The Revenant", "genres": "Drama Adventure Thriller"},
    {"title": "Birdman", "genres": "Comedy Drama"},
    {"title": "Madagascar", "genres": "Animation Family Comedy"},
    {"title": "Shrek", "genres": "Animation Family Comedy Fantasy"},
    {"title": "Moana", "genres": "Animation Family Adventure"},
    {"title": "Frozen", "genres": "Animation Family Fantasy Musical"},
    {"title": "Tangled", "genres": "Animation Family Comedy Fantasy"},
    {"title": "The Incredibles", "genres": "Animation Family Action"},
    {"title": "Up", "genres": "Animation Family Adventure Comedy"},
    {"title": "Inside Out", "genres": "Animation Family Comedy"},
    {"title": "Kill Bill: Vol. 1", "genres": "Action Crime Thriller"},
    {"title": "Reservoir Dogs", "genres": "Crime Thriller Drama"},
    {"title": "Taxi Driver", "genres": "Drama Crime Thriller"},
    {"title": "Raging Bull", "genres": "Drama Biography Sport"},
    {"title": "Apocalypse Now", "genres": "War Drama"},
    {"title": "Platoon", "genres": "War Drama Action"},
    {"title": "Fury", "genres": "War Drama Action"},
    {"title": "Black Panther", "genres": "Action Sci-Fi Adventure"},
    {"title": "Iron Man", "genres": "Action Sci-Fi Adventure"},
    {"title": "Thor", "genres": "Action Fantasy Adventure"},
    {"title": "Captain America: The Winter Soldier", "genres": "Action Sci-Fi Thriller"},
    {"title": "Doctor Strange", "genres": "Action Fantasy Sci-Fi"},
    {"title": "Ant-Man", "genres": "Action Comedy Sci-Fi"},
    {"title": "Dead Poets Society", "genres": "Drama Comedy"},
    {"title": "Good Will Hunting", "genres": "Drama Romance"},
    {"title": "A Beautiful Mind", "genres": "Drama Biography Romance"},
    {"title": "Rain Man", "genres": "Drama Comedy"},
    {"title": "The Pursuit of Happyness", "genres": "Drama Biography"},
    {"title": "Slumdog Millionaire", "genres": "Drama Romance Crime"},
    {"title": "The King's Speech", "genres": "Drama History Biography"},
    {"title": "1917", "genres": "War Drama History"},
    {"title": "Dunkirk", "genres": "War Drama Action"},
    {"title": "Blade Runner", "genres": "Sci-Fi Thriller Action"},
    {"title": "Blade Runner 2049", "genres": "Sci-Fi Thriller Mystery"},
    {"title": "Arrival", "genres": "Sci-Fi Drama Mystery"},
    {"title": "Gravity", "genres": "Sci-Fi Thriller Adventure"},
    {"title": "The Martian", "genres": "Sci-Fi Adventure Drama"},
    {"title": "Wall-E", "genres": "Animation Sci-Fi Family"},
    {"title": "Ratatouille", "genres": "Animation Family Comedy"},
    {"title": "Kung Fu Panda", "genres": "Animation Family Comedy Action"},
    {"title": "How to Train Your Dragon", "genres": "Animation Family Fantasy Adventure"},
    {"title": "Despicable Me", "genres": "Animation Family Comedy"},
    {"title": "Minions", "genres": "Animation Family Comedy"},
    {"title": "Hotel Transylvania", "genres": "Animation Family Comedy Fantasy"},
    {"title": "The Conjuring", "genres": "Horror Mystery Thriller"},
    {"title": "Annabelle", "genres": "Horror Mystery Thriller"},
    {"title": "It", "genres": "Horror Thriller"},
    {"title": "The Nun", "genres": "Horror Mystery Thriller"},
    {"title": "Halloween", "genres": "Horror Thriller"},
    {"title": "Nightmare on Elm Street", "genres": "Horror Thriller"},
    {"title": "Scream", "genres": "Horror Mystery Thriller"},
    {"title": "Training Day", "genres": "Crime Drama Thriller"},
    {"title": "Heat", "genres": "Crime Drama Thriller Action"},
    {"title": "Collateral", "genres": "Crime Thriller Action"},
    {"title": "The Fugitive", "genres": "Action Thriller Crime Mystery"},
    {"title": "Taken", "genres": "Action Thriller Crime"},
    {"title": "Die Hard", "genres": "Action Thriller"},
    {"title": "Lethal Weapon", "genres": "Action Comedy Crime"},
    {"title": "Rocky", "genres": "Drama Sport"},
    {"title": "Creed", "genres": "Drama Sport"},
    {"title": "Moneyball", "genres": "Drama Biography Sport"},
    {"title": "The Blind Side", "genres": "Drama Biography Sport"},
    {"title": "Remember the Titans", "genres": "Drama Sport"},
    {"title": "Miracle", "genres": "Drama Sport"},
    {"title": "The Dark Knight Rises", "genres": "Action Crime Thriller"},
    {"title": "Batman Begins", "genres": "Action Crime Thriller"},
    {"title": "Superman", "genres": "Action Sci-Fi Adventure"},
    {"title": "Shazam!", "genres": "Action Comedy Fantasy"},
    {"title": "Aquaman", "genres": "Action Fantasy Adventure"},
    {"title": "The Batman", "genres": "Crime Thriller Mystery Action"},
    {"title": "Avatar: The Way of Water", "genres": "Action Sci-Fi Adventure"},
    {"title": "Top Gun: Maverick", "genres": "Action Drama Thriller"},
    {"title": "Oppenheimer", "genres": "Drama History Biography Thriller"},
    {"title": "Barbie", "genres": "Comedy Fantasy Adventure"},
    {"title": "Dune", "genres": "Sci-Fi Adventure Drama"},
    {"title": "Dune: Part Two", "genres": "Sci-Fi Adventure Drama"},
    {"title": "The Hunger Games", "genres": "Sci-Fi Action Adventure"},
    {"title": "Divergent", "genres": "Sci-Fi Action Adventure"},
    {"title": "The Maze Runner", "genres": "Sci-Fi Action Mystery"},
    {"title": "Twilight", "genres": "Romance Fantasy Drama"},
    {"title": "The Fault in Our Stars", "genres": "Romance Drama"},
    {"title": "A Star Is Born", "genres": "Romance Drama Musical"},
    {"title": "Crazy Rich Asians", "genres": "Romance Comedy"},
    {"title": "10 Things I Hate About You", "genres": "Romance Comedy"},
    {"title": "She's the Man", "genres": "Romance Comedy"},
    {"title": "The Proposal", "genres": "Romance Comedy"},
    {"title": "How to Lose a Guy in 10 Days", "genres": "Romance Comedy"},
    {"title": "Bridesmaids", "genres": "Comedy"},
    {"title": "Superbad", "genres": "Comedy"},
    {"title": "The Hangover", "genres": "Comedy"},
    {"title": "Knocked Up", "genres": "Comedy Romance"},
    {"title": "Anchorman", "genres": "Comedy"},
    {"title": "Step Brothers", "genres": "Comedy"},
    {"title": "Napoleon Dynamite", "genres": "Comedy"},
    {"title": "Juno", "genres": "Comedy Drama"},
    {"title": "Little Miss Sunshine", "genres": "Comedy Drama"},
    {"title": "The 40-Year-Old Virgin", "genres": "Comedy Romance"},
    {"title": "Zombieland", "genres": "Comedy Horror"},
    {"title": "Shaun of the Dead", "genres": "Comedy Horror"},
    {"title": "Clerks", "genres": "Comedy"},
    {"title": "Office Space", "genres": "Comedy"},
    {"title": "Elf", "genres": "Comedy Fantasy Family"},
    {"title": "Home Alone", "genres": "Comedy Family"},
    {"title": "The Grinch", "genres": "Comedy Family Fantasy"},
    {"title": "Polar Express", "genres": "Animation Family Fantasy Adventure"},
    {"title": "A Christmas Story", "genres": "Comedy Family"},
    {"title": "Die Hard 2", "genres": "Action Thriller"},
    {"title": "Casino", "genres": "Crime Drama"},
    {"title": "Scarface", "genres": "Crime Drama"},
    {"title": "The Irishman", "genres": "Crime Drama Biography"},
    {"title": "Donnie Brasco", "genres": "Crime Drama Biography"},
    {"title": "American Gangster", "genres": "Crime Drama Biography"},
    {"title": "Snatch", "genres": "Comedy Crime"},
    {"title": "Lock, Stock and Two Smoking Barrels", "genres": "Comedy Crime"},
    {"title": "The Big Lebowski", "genres": "Comedy Crime"},
    {"title": "Fargo", "genres": "Crime Drama Thriller"},
    {"title": "The Usual Suspects", "genres": "Crime Thriller Mystery"},
    {"title": "The Sixth Sense", "genres": "Thriller Mystery Drama"},
    {"title": "Unbreakable", "genres": "Thriller Sci-Fi Mystery"},
    {"title": "Split", "genres": "Thriller Horror"},
    {"title": "Glass", "genres": "Thriller Drama Sci-Fi"},
    {"title": "Oldboy", "genres": "Thriller Mystery Action"},
    {"title": "Requiem for a Dream", "genres": "Drama Thriller"},
    {"title": "Black Swan", "genres": "Drama Thriller Mystery"},
    {"title": "Bird Box", "genres": "Horror Sci-Fi Thriller"},
    {"title": "World War Z", "genres": "Horror Action Sci-Fi"},
    {"title": "I Am Legend", "genres": "Sci-Fi Horror Thriller"},
    {"title": "The Day After Tomorrow", "genres": "Sci-Fi Thriller Disaster"},
    {"title": "2012", "genres": "Sci-Fi Action Disaster"},
    {"title": "San Andreas", "genres": "Action Disaster Adventure"},
    {"title": "Twister", "genres": "Action Adventure Disaster"},
    {"title": "Poseidon", "genres": "Action Adventure Disaster"},
    {"title": "The Abyss", "genres": "Sci-Fi Thriller"},
    {"title": "Deep Impact", "genres": "Sci-Fi Disaster Drama"},
    {"title": "Independence Day", "genres": "Sci-Fi Action Disaster"},
    {"title": "Godzilla", "genres": "Action Sci-Fi Thriller"},
    {"title": "King Kong", "genres": "Action Adventure Drama"},
    {"title": "Pacific Rim", "genres": "Action Sci-Fi Adventure"},
    {"title": "Transformers", "genres": "Action Sci-Fi Adventure"},
    {"title": "Men in Black", "genres": "Action Comedy Sci-Fi"},
    {"title": "Ghostbusters", "genres": "Comedy Sci-Fi Fantasy"},
    {"title": "Goonies", "genres": "Adventure Comedy Family"},
    {"title": "Jumanji", "genres": "Adventure Comedy Fantasy"},
    {"title": "The Jungle Book", "genres": "Adventure Family Fantasy"},
    {"title": "Pirates of the Caribbean", "genres": "Action Adventure Fantasy"},
    {"title": "National Treasure", "genres": "Action Adventure Mystery"},
    {"title": "Indiana Jones and the Raiders of the Lost Ark", "genres": "Adventure Action"},
    {"title": "The Mummy", "genres": "Action Adventure Fantasy"},
    {"title": "The Da Vinci Code", "genres": "Thriller Mystery Crime"},
    {"title": "Sherlock Holmes", "genres": "Action Mystery Crime"},
    {"title": "The Bourne Identity", "genres": "Action Thriller Mystery"},
    {"title": "Casino Royale", "genres": "Action Thriller Adventure"},
    {"title": "Skyfall", "genres": "Action Thriller Adventure"},
    {"title": "The Equalizer", "genres": "Action Thriller Crime"},
    {"title": "Jack Reacher", "genres": "Action Crime Thriller"},
    {"title": "The Accountant", "genres": "Action Crime Thriller"},
    {"title": "Baby Driver", "genres": "Action Crime Musical"},
    {"title": "Drive", "genres": "Crime Drama Thriller"},
    {"title": "Nightcrawler", "genres": "Crime Drama Thriller"},
    {"title": "Gone Girl", "genres": "Thriller Crime Mystery"},
    {"title": "The Girl with the Dragon Tattoo", "genres": "Crime Thriller Mystery"},
    {"title": "Prisoners", "genres": "Thriller Crime Drama"},
    {"title": "Mystic River", "genres": "Crime Drama Mystery"},
    {"title": "Shutter Island", "genres": "Thriller Mystery Drama"},
    {"title": "The Machinist", "genres": "Thriller Mystery Drama"},
    {"title": "The Ring", "genres": "Horror Mystery Thriller"},
    {"title": "Insidious", "genres": "Horror Mystery Thriller"},
    {"title": "Sinister", "genres": "Horror Mystery"},
    {"title": "Paranormal Activity", "genres": "Horror Mystery"},
    {"title": "The Purge", "genres": "Horror Thriller"},
    {"title": "Gerald's Game", "genres": "Horror Thriller"},
    {"title": "Doctor Sleep", "genres": "Horror Thriller Fantasy"},
    {"title": "IT Chapter Two", "genres": "Horror Thriller"},
    {"title": "Us", "genres": "Horror Thriller Mystery"},
    {"title": "Hereditary", "genres": "Horror Mystery Drama"},
    {"title": "The Witch", "genres": "Horror Mystery Drama"},
    {"title": "Midsommar", "genres": "Horror Drama Mystery"},
    {"title": "A Quiet Place Part II", "genres": "Horror Sci-Fi Thriller"},
    {"title": "Soul", "genres": "Animation Family Comedy Fantasy"},
    {"title": "Luca", "genres": "Animation Family Comedy Fantasy"},
    {"title": "Encanto", "genres": "Animation Family Fantasy Musical"},
    {"title": "Turning Red", "genres": "Animation Family Comedy"},
    {"title": "Onward", "genres": "Animation Family Fantasy Adventure"},
    {"title": "Raya and the Last Dragon", "genres": "Animation Family Fantasy Adventure"},
    {"title": "The Good Dinosaur", "genres": "Animation Family Adventure"},
    {"title": "Brave", "genres": "Animation Family Fantasy Adventure"},
    {"title": "Big Hero 6", "genres": "Animation Family Action Sci-Fi"},
    {"title": "Wreck-It Ralph", "genres": "Animation Family Comedy"},
    {"title": "Frozen II", "genres": "Animation Family Fantasy Musical"},
    {"title": "Toy Story 2", "genres": "Animation Family Comedy"},
    {"title": "Toy Story 3", "genres": "Animation Family Comedy"},
    {"title": "Toy Story 4", "genres": "Animation Family Comedy"},
    {"title": "Monsters Inc", "genres": "Animation Family Comedy"},
    {"title": "Cars", "genres": "Animation Family Comedy Sport"},
    {"title": "Finding Dory", "genres": "Animation Family Adventure"},
    {"title": "Incredibles 2", "genres": "Animation Family Action"},
    {"title": "The Princess and the Frog", "genres": "Animation Family Fantasy Musical"},
    {"title": "Aladdin", "genres": "Animation Family Fantasy Musical"},
    {"title": "Beauty and the Beast", "genres": "Animation Family Fantasy Musical"},
    {"title": "The Little Mermaid", "genres": "Animation Family Fantasy Musical"},
    {"title": "Sleeping Beauty", "genres": "Animation Family Fantasy Musical"},
    {"title": "Snow White", "genres": "Animation Family Fantasy Musical"},
    {"title": "Cinderella", "genres": "Animation Family Fantasy Musical"},
    {"title": "Pinocchio", "genres": "Animation Family Fantasy"},
    {"title": "Bambi", "genres": "Animation Family Drama"},
    {"title": "Dumbo", "genres": "Animation Family Fantasy"},
    {"title": "Fantasia", "genres": "Animation Family Musical"},
    {"title": "Horton Hears a Who", "genres": "Animation Family Comedy"},
    {"title": "Ice Age", "genres": "Animation Family Adventure Comedy"},
    {"title": "Rio", "genres": "Animation Family Comedy Adventure"},
    {"title": "Megamind", "genres": "Animation Family Comedy Action"},
    {"title": "The Croods", "genres": "Animation Family Adventure Comedy"},
    {"title": "Sing", "genres": "Animation Family Comedy Musical"},
    {"title": "The Angry Birds Movie", "genres": "Animation Family Comedy"},
    {"title": "Boss Baby", "genres": "Animation Family Comedy"},
    {"title": "The Secret Life of Pets", "genres": "Animation Family Comedy"},
    {"title": "Hotel Transylvania 2", "genres": "Animation Family Comedy Fantasy"},
    {"title": "Sausage Party", "genres": "Animation Comedy"},
    {"title": "Wreck-It Ralph 2", "genres": "Animation Family Comedy"},
]
